### ISSUE TITLE
Add gitlab scope to the hiera config

### ISSUE THREAD

**Issue by minorOffense** [spuder/puppet-gitlab#71]
Right now, it would appear that all the hiera config sits at the top level in the yaml array. Should it not be nested similarly to how "apache" and "mysql" hiera config are?

Ex:

``` yaml
gitlab:
  external_url: gitlab.example.com
  gitlab_branch: 7.2.0
```
